### ISSUE TITLE
Test MARKET Order

### ISSUE THREAD

**Issue by baloo98** [taskula/binance-perl-api#13]
Hi Lari,

As precedent issue is closed, and I don't know where send the error find, I onpen a new one for the test, may be 

I test the upgrade realese for market Order;
For BUY MARKET test using $api->order_test(
I test with quoteOrderQty parameter, and it's look like your are only waiting quantity parameter for market order.
So I test with quantity parameter and it look like also waiting price but it's not require for market order if I understand Binance doc.
For SELL MARKET order, it is logicaly the same error.

Adding price give a new error
[Binance::API::Request::_exec] Bad Request at /usr/local/share/perl/5.30.0/Binance/API/Request.pm line 105.

How need I do ?

Regards

**Comment by taskula** [comment]
Hi,

According to
https://github.com/binance-exchange/binance-official-api-docs/blob/7a8d958157d3c0ed8ddaead8d1c0273ec9a3504e/rest-api.md#new-order--trade

Required parameters for all types are:

*symbol*, *side*, *type

*This is set in
https://github.com/taskula/binance-perl-api/blob/6aea9627b435ec3ebf8cb24a4b974ade56c0789c/lib/Binance/API.pm#L858-L860
*
*Additionally, mandatory parameters for *type=MARKET* are *quantity* or
*quoteOrderQty*. This is set in
https://github.com/taskula/binance-perl-api/blob/6aea9627b435ec3ebf8cb24a4b974ade56c0789c/lib/Binance/API.pm#L880-L887

*price* is an optional parameter.

Please provide me code so that easy for me to test.

Lari Taskula
CEO, Hypernova Oy
PL 16
80101 Joensuu, Finland

**Comment by taskula** [comment]
Hi,

According to
https://github.com/binance-exchange/binance-official-api-docs/blob/7a8d958157d3c0ed8ddaead8d1c0273ec9a3504e/rest-api.md#new-order--trade

Required parameters for all types are:

*symbol*, *side*, *type*

This is set in
https://github.com/taskula/binance-perl-api/blob/6aea9627b435ec3ebf8cb24a4b974ade56c0789c/lib/Binance/API.pm#L850-L856 and https://github.com/taskula/binance-perl-api/blob/6aea9627b435ec3ebf8cb24a4b974ade56c0789c/lib/Binance/API.pm#L858-L860

Additionally, mandatory parameters for *type=MARKET* are *quantity* or *quoteOrderQty*. This is set in
https://github.com/taskula/binance-perl-api/blob/6aea9627b435ec3ebf8cb24a4b974ade56c0789c/lib/Binance/API.pm#L880-L887

*price* is an optional parameter.

Please provide me code so that easy for me to test.

**Comment by baloo98** [comment]
Hi Lari,

Thank's for your return,

here it is my code for BUY FROM a form 
($crypto[0] = "BTC"  for example)

$prix=$api->ticker_price( symbol => $crypto[0]."USDT" ); 
$qtecrypto=$value_from_form/$prix->{"price"}; 

$retAPI=$api->order_test(
#$retAPI=$api->order(
    symbol => "'".$crypto[0]."USDT'",
    side   => 'BUY',
    type   => 'MARKET',
    timeInForce => 'GTC',
    quantity => $qtecrypto
);

Regard

**Comment by taskula** [comment]
And what error are you getting? You can run your script with `BINANCE_API_DEBUG=1 perl your_test_script.pl` to see more info.

> symbol => "'".$crypto[0]."USDT'",

Firstly, this should be `symbol => $crypto[0].'USDT',`

> timeInForce => 'GTC',

Secondly, this seems to return

```
[Binance::API::Request::_exec] Unsuccessful request. 
Status => 400,
Content => {"code":-1106,"msg":"Parameter 'timeInForce' sent when not required."} at lib/Binance/API/Request.pm line 107.
```

Thirdly, if your `$qtecrypto` is wrongly formatted, you might receive

```
[Binance::API::Request::_exec] Unsuccessful request. 
Status => 400,
Content => {"code":-1013,"msg":"Invalid quantity."} at lib/Binance/API/Request.pm line 107.
```
and
```
[Binance::API::Request::_exec] Unsuccessful request. 
Status => 400,
Content => {"code":-1111,"msg":"Precision is over the maximum defined for this asset."} at lib/Binance/API/Request.pm line 107.
```

**Comment by baloo98** [comment]
Thank's

1) symbol, ok.
2) timeInForce, if i don't sent it, here it is the answer : 
    [Binance::API::order_test] Parameter "timeInForce" required at /usr/local/share/perl/5.30.0/Binance/API.pm line 922
3) quantity value I will have a look about precision.

**Comment by taskula** [comment]
>     2. timeInForce, if i don't sent it, here it is the answer :
>        [Binance::API::order_test] Parameter "timeInForce" required at /usr/local/share/perl/5.30.0/Binance/API.pm line 922

Ok, you are using an older version of the module. Try installing the latest version 1.05.

Running `cpan Binance::API` at your command line interface should do.

**Comment by baloo98** [comment]
Hi Lary,

After looking precision, and compare error message, I realize that I don't upgrade my lib from your last released.
every thing look good with 1.5. with test.
I need to sleep or take some holiday, ...

I'll give a return after some market orders soon.

Regard

**Comment by baloo98** [comment]
After some time needed to adjust the precision, for the sell order, it work fine for buy and sell in spot market order.

thank's Lari for this good job.

regard
